const API_BASE_URL = 'http://127.0.0.1:5000/api';
const BASE_URL = 'http://127.0.0.1:5000';
const Constants = {
  API_BASE_URL,
  BASE_URL,
  LOGIN_URL: `${API_BASE_URL}/auth/login`,
  FETCH_USER_PROFILE_URL: `${API_BASE_URL}/admin/profile`,
  FETCH_COUNTRIES_URL: `${API_BASE_URL}/admin/countries`,
  FETCH_STATES_URL: `${API_BASE_URL}/admin/states`,
  FETCH_CITIES_URL: `${API_BASE_URL}/admin/cities`,
  UPDATE_PROFILE_URL: `${API_BASE_URL}/admin/profile`,
  FETCH_UNITS_URL: `${API_BASE_URL}/admin/units`,
  CREATE_UNIT_URL: `${API_BASE_URL}/admin/units`,
  GET_UNIT_URL: `${API_BASE_URL}/admin/units`,
  UPDATE_UNIT_URL: `${API_BASE_URL}/admin/units`,
  DELETE_UNIT_URL: `${API_BASE_URL}/admin/units`,
  CREATE_BRAND_URL: `${API_BASE_URL}/admin/brands`,
  FETCH_BRAND_LIST_URL: `${API_BASE_URL}/admin/brands`,
  GET_BRAND_URL: `${API_BASE_URL}/admin/brands`,
  UPDATE_BRAND_URL: `${API_BASE_URL}/admin/brands`,
  DELETE_BRAND_URL: `${API_BASE_URL}/admin/brands`,
  FETCH_CATEGORY_LIST_URL: `${API_BASE_URL}/admin/categories`,
  CREATE_CATEGORY_URL: `${API_BASE_URL}/admin/categories`,
  UPDATE_CATEGORY_URL: `${API_BASE_URL}/admin/categories`,
  GET_CATEGORY_URL: `${API_BASE_URL}/admin/categories`,
  DELETE_CATEGORY_URL: `${API_BASE_URL}/admin/categories`,
  CREATE_TAX_RATE_URL: `${API_BASE_URL}/admin/tax-rates`,
  FETCH_TAX_RATE_LIST_URL: `${API_BASE_URL}/admin/tax-rates`,
  GET_TAX_RATE_URL: `${API_BASE_URL}/admin/tax-rates`,
  UPDATE_TAX_RATE_URL: `${API_BASE_URL}/admin/tax-rates`,
  DELETE_TAX_RATE_URL: `${API_BASE_URL}/admin/tax-rates`,
  FETCH_TAX_GROUP_LIST_URL: `${API_BASE_URL}/admin/tax-groups`,
  CREATE_TAX_GROUP_URL: `${API_BASE_URL}/admin/tax-groups`,
  GET_TAX_GROUP_URL: `${API_BASE_URL}/admin/tax-groups`,
  UPDATE_TAX_GROUP_URL: `${API_BASE_URL}/admin/tax-groups`,
  DELETE_TAX_GROUP_URL: `${API_BASE_URL}/admin/tax-groups`,
  FETCH_PRODUCTS_URL: `${API_BASE_URL}/admin/products`,
  GET_PRODUCT_URL: `${API_BASE_URL}/admin/products`,
  FETCH_PRODUCT_CATEGORIES_URL: `${API_BASE_URL}/admin/product-categories`,
  FETCH_PRODUCT_BRANDS_URL: `${API_BASE_URL}/admin/product-brands`,
  FETCH_PRODUCT_UNITS_URL: `${API_BASE_URL}/admin/product-units`,
  FETCH_PRODUCT_TAXES_URL: `${API_BASE_URL}/admin/product-taxes`,
  CREATE_PRODUCT_URL: `${API_BASE_URL}/admin/products`,
  UPDATE_PRODUCT_URL: `${API_BASE_URL}/admin/products`,
  DELETE_PRODUCT_URL: `${API_BASE_URL}/admin/products`,
  CREATE_SUPPLIER_URL: `${API_BASE_URL}/admin/suppliers`,
  GET_SUPPLIERS_URL: `${API_BASE_URL}/admin/suppliers`,
  UPDATE_SUPPLIER_URL: `${API_BASE_URL}/admin/suppliers`,
  DELETE_SUPPLIER_URL: `${API_BASE_URL}/admin/suppliers`
};

export default Constants;
